title: 🌵 US Drought Monitor Archive
description: An archive of the US Drought Monitor weekly drought assessment
author: R. Kyle Bocinsky
url: "https://strong-fsa.github.io/usdm/"  # Your GitHub Pages URL
baseurl: "/usdm"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# minima:
#   skin: classic