# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  schedule:
    - cron: '49 12 * * THU'

name: update
run-name: Update the USDM Archive with the latest data! 🚀

permissions: write-all

jobs:
  update-usdm:
    name: update-usdm
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - name: install-deps
        run: |
          add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          apt update
          apt install libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite3-dev
      
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: run
        run: |
          Rscript usdm.R
          
      - uses: gacts/directory-listing@v1
        with:
          target: ./usdm
          ignore: |
            **/index.html
          show-hidden: false
          overwrite: true
  
      - name: Commit and push changes
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Auto-generate index.html for directory listing" || echo "No changes to commit"
          git push
          
  # generate-index:
  #   runs-on: ubuntu-latest
  #   needs: update-usdm
  #   steps:
  #     - uses: actions/checkout@v4
  #     
  #     - uses: gacts/directory-listing@v1
  #       with:
  #         target: ./usdm
  #         ignore: |
  #           **/index.html
  #         show-hidden: false
  #         overwrite: true
  # 
  #     - name: Commit and push changes
  #       run: |
  #         git config --global user.name "$GITHUB_ACTOR"
  #         git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
  #         git add .
  #         git commit -m "Auto-generate index.html for directory listing" || echo "No changes to commit"
  #         git push